---
- name: add user
  hosts: test
  vars:
    ansible_host_key_checking: false 
  become: true
  tasks:
        - name: create a user name vasee
          user:
                name: vasee
                uid: 1002
                state: present
